title: Jerry Smith
email: "jsmith@jerry-smith.net"
description: Jerry Smith - Red Hat Certified Architect IV 111-064-523
repository: "dean1012/dean1012.github.io"
github_url: https://github.jerry-smith.net
gitlab_url: https://gitlab.jerry-smith.net
bitcoin_address: 32MQsRxDzVcemUZbtWEVgQh2EZZmbGcQfs
paypal_url: https://payments.jerry-smith.net
gpg_key_url: https://gpg.jerry-smith.net
certification_name: Red Hat Certified Architect IV
certification_id: 111-064-523
verify_url: https://verify.jerry-smith.net
discord_url: https://discord.jerry-smith.net
bitbucket_url: https://bitbucket.jerry-smith.net
testimonials_url: https://testimonials.jerry-smith.net
reddit_url: https://reddit.jerry-smith.net

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-redirect-from
  - jemoji

header_pages:
  - index.md
  - hire.md

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - start_test_server.sh
